# Generated by Django 3.2.5 on 2021-11-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alaye_blog', '0005_auto_20211115_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
